CREATE DATABASE IF NOT EXISTS BTL_CNPM;
USE BTL_CNPM;
CREATE TABLE User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Phone VARCHAR(11),
    Role ENUM('Tutor','Student') NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CHECK (FullName <> ''),
    CHECK (Email <> ''),
    CHECK (CHAR_LENGTH(Password) >= 8)
);
CREATE TABLE Tutor (
    TutorID INT PRIMARY KEY,
    Specialization VARCHAR(100),
    ExperienceYears INT CHECK (ExperienceYears >= 0),
    Qualification VARCHAR(100),
    Rating DECIMAL(2,1) DEFAULT 0.0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TutorID) REFERENCES User(UserID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TutorAvailability (
    AvailabilityID INT AUTO_INCREMENT PRIMARY KEY,
    TutorID INT NOT NULL,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TutorID) REFERENCES Tutor(TutorID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Student (
    StudentID INT PRIMARY KEY,
    StudentCode VARCHAR(20) UNIQUE NOT NULL,
    GPA DECIMAL(3,2) CHECK (GPA >= 0.00 AND GPA <= 4.00),
    Major VARCHAR(100),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (StudentID) REFERENCES User(UserID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE StudentCourse (
    StudentCourseID INT AUTO_INCREMENT PRIMARY KEY,
    StudentID INT NOT NULL,
    CourseName VARCHAR(100) NOT NULL,
    RegistrationAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('Active', 'Completed', 'Dropped') DEFAULT 'Active',
    FOREIGN KEY (StudentID) REFERENCES Student(StudentID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MatchingCourse (
    MatchID INT AUTO_INCREMENT PRIMARY KEY,
    TutorID INT NOT NULL,
    StudentID INT NOT NULL,
    MatchDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    MatchType ENUM('Manual', 'Auto') DEFAULT 'Auto',
    Status ENUM('Pending', 'Matched', 'Rejected') DEFAULT 'Pending',
    FOREIGN KEY (TutorID) REFERENCES Tutor(TutorID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (StudentID) REFERENCES Student(StudentID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LessonSchedule (
    LessonID INT AUTO_INCREMENT PRIMARY KEY,
    MatchID INT NOT NULL,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    Status ENUM('Scheduled', 'Completed', 'Cancelled') DEFAULT 'Scheduled',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastUpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (MatchID) REFERENCES MatchingCourse(MatchID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LessonFeedback (
    FeedbackID INT AUTO_INCREMENT PRIMARY KEY,
    LessonID INT NOT NULL,
    Rating INT CHECK (Rating BETWEEN 1 AND 5),
    Comment TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LessonID) REFERENCES LessonSchedule(LessonID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
